apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
    - name: config_container
      image: nginx
      ports: 
        - containerPort: 80 
      env:
      - name: 
        valueFrom:
          configMapKeyRef: 
            name: devops-config
            key: course
      - name: 
        valueFrom:
          configMapKeyRef: 
            name: devops-config
            key: trainer