apiVersion: v1
kind: Pod
metadata:
  name: configpod
spec:
  containers:
    - name: configcontainer
      image: nginx
      ports: 
        - containerPort: 80 
      env:
      - name: one
        valueFrom:
          configMapKeyRef: 
            name: devops-config
            key: course
      - name: two
        valueFrom:
          configMapKeyRef: 
            name: devops-config
            key: trainer