apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod

spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests: #soft limit (allocated limit)
        cpu: "250m"
        memory: "68Mi"
      limits: #Extension limit
        cpu: "500m"
        memory: "128Mi"
  