apiVersion: v1
kind: Pod
metadata:
  name: secretpod
spec:
  containers:
    - name: secretcontainer
      image: nginx
      ports: 
        - containerPort: 80 
      envFrom:
      - secretRef:
          name: devops-secret