apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: service-app
    demo: service

spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: service-app
    demo: service
  ports:
    - protocol: TCP
      port: 80 #serviceport
      targetPort: 80 #containerport

